server:
  port: 8080

spring:
  application:
    name: "foo"
  cache:
    type: CAFFEINE

redis:
  host: localhost
  port: 6379
  password: "Avaya@123!"

mockData: false
useCacheRepo: true
cache:
  initialCap: 300
  maxSize: 900
  expireAfterAccessInSeconds: 30

# Asynchronous write ThreadPool Configuration
async:
  core:
    write-pool-size: 512
    read-pool-size: 512
  max:
    write-pool-size: 768
    read-pool-size: 768
  pool:
    queue:
      capacity: 1024